// Shared PR-policy rules for .github/workflows/pr-validation.yml and
// .github/workflows/pr-license-enforcement.yml.
//
// Both workflows must agree on who is exempt, what the license checkbox looks
// like, and how long the grace period is. Keeping the rules in one module means
// a change lands in both places at once instead of drifting.
//
// Loaded from actions/github-script via:
//   const policy = require(`${process.env.GITHUB_WORKSPACE}/.github/scripts/pr-policy.cjs`);
//
// Both workflows check out the BASE branch (never PR head), so a pull request
// cannot change the rules that judge it.

const LICENSE_LABEL = 'integrity-license-pending';
const LICENSE_LABEL_COLOR = 'b60205';
const LICENSE_LABEL_DESCRIPTION =
  'Integrity & license agreement pending; PR closes 7 days after this label was applied';

const LICENSE_ITEM = '[MANDATORY - ALL] Integrity & License';
const LICENSE_ITEM_TEXT =
  '**[MANDATORY - ALL] Integrity & License**: I certify this is my own work, free of malicious code, and I agree to the [License terms](https://github.com/CodeWithCJ/SparkyFitness/blob/main/LICENSE).';

const GRACE_MS = 7 * 24 * 60 * 60 * 1000;

// Deliberately owner-only. On a user-owned repo `OWNER` is exactly one person --
// the account that owns the repo (CodeWithCJ) -- so this is "the maintainer and
// nobody else", expressed without hardcoding a username.
//
// Other collaborators are NOT exempt: they tick the license box like everyone
// else. Add 'COLLABORATOR' here only if that should change.
const EXEMPT_ASSOCIATIONS = ['OWNER'];

// Head-branch prefixes used by this repo's own automation. Only consulted for
// branches pushed directly to this repo (see rule 3 in getExemption).
const AUTOMATION_BRANCH_PREFIXES = [
  'ci/',          // schema-backup.yml       -> ci/schema-backup-sync
  'nix/',         // nix-update-hashes.yml   -> nix/update-pnpm-hashes
  'i18n/',        // sync-translations.yml   -> i18n/update-english-locales,
                  //                            i18n/sync-weblate-translations
  'dependabot/',
  'renovate/',
];

const escapeRegex = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// "- [x] **<item>" / "- [X] **<item>"
const isChecked = (body, item) =>
  new RegExp(`-\\s*\\[[xX]\\]\\s*\\*\\*${escapeRegex(item)}`, 'i').test(body || '');

// Same line, ticked or not. A missing box means the template was deleted and we
// add it back; an unticked box is the contributor's job.
const isPresent = (body, item) =>
  new RegExp(`-\\s*\\[[ xX]\\]\\s*\\*\\*${escapeRegex(item)}`, 'i').test(body || '');

/**
 * Decide whether a PR is exempt from the license agreement requirement.
 *
 * Accepts either `context.payload.pull_request` or an element of
 * `pulls.list` — both carry `user`, `author_association`, `head`, and `base`.
 *
 * @returns {{exempt: boolean, reason: string}}
 */
function getExemption(pr) {
  // 1. Any bot account.
  //
  //    This is the rule that makes FUTURE automation exempt with no edit here.
  //    Every workflow that opens a PR with the default GITHUB_TOKEN is authored
  //    by github-actions[bot], and every GitHub App (Dependabot, Renovate,
  //    anything installed later) is likewise user.type === 'Bot'. Covers today's
  //    schema-backup.yml, nix-update-hashes.yml and sync-translations.yml, and
  //    anything added tomorrow.
  if (pr.user && pr.user.type === 'Bot') {
    return { exempt: true, reason: `bot account (${pr.user.login})` };
  }

  // 2. The repo owner. Also covers PAT-driven automation whose token belongs to
  //    the owner, which appears as a normal User rather than a Bot (e.g.
  //    TRANSLATIONS_PAT in sync-translations.yml). If that PAT belongs to
  //    someone else, rule 3 below still covers it via the branch name.
  if (EXEMPT_ASSOCIATIONS.includes(pr.author_association)) {
    return { exempt: true, reason: `repo ${String(pr.author_association).toLowerCase()}` };
  }

  // 3. Automation branches pushed directly to this repo. Safety net for a
  //    service account that is neither a Bot nor a collaborator.
  //
  //    Deliberately restricted to same-repo branches: pushing a branch to this
  //    repo already requires write access, so an outside contributor cannot
  //    claim the exemption by naming their fork branch `ci/anything`.
  const headRepo = pr.head && pr.head.repo && pr.head.repo.full_name;
  const baseRepo = pr.base && pr.base.repo && pr.base.repo.full_name;
  const headRef = (pr.head && pr.head.ref) || '';
  if (headRepo && baseRepo && headRepo === baseRepo) {
    if (AUTOMATION_BRANCH_PREFIXES.some(prefix => headRef.startsWith(prefix))) {
      return { exempt: true, reason: `automation branch (${headRef})` };
    }
  }

  return { exempt: false, reason: '' };
}

/**
 * Is this PR machine-generated by our own automation?
 *
 * Narrower than getExemption: a human collaborator is exempt from the LICENSE
 * requirement but is still held to the contributor checklist. A bot is held to
 * neither — the weblate sync PR legitimately rewrites non-English locale files,
 * the schema-backup PR carries no template at all, and neither can tick a box.
 */
function isAutomation(pr) {
  if (pr.user && pr.user.type === 'Bot') return true;

  const headRepo = pr.head && pr.head.repo && pr.head.repo.full_name;
  const baseRepo = pr.base && pr.base.repo && pr.base.repo.full_name;
  const headRef = (pr.head && pr.head.ref) || '';
  return Boolean(
    headRepo && baseRepo && headRepo === baseRepo &&
    AUTOMATION_BRANCH_PREFIXES.some(prefix => headRef.startsWith(prefix))
  );
}

module.exports = {
  LICENSE_LABEL,
  LICENSE_LABEL_COLOR,
  LICENSE_LABEL_DESCRIPTION,
  LICENSE_ITEM,
  LICENSE_ITEM_TEXT,
  GRACE_MS,
  EXEMPT_ASSOCIATIONS,
  AUTOMATION_BRANCH_PREFIXES,
  escapeRegex,
  isChecked,
  isPresent,
  getExemption,
  isAutomation,
};
