export const DEFAULT_GOALS = {
  calories: 2000,
  protein: 150,
  carbs: 250,
  fat: 67,
  water_goal_ml: 1920, // Default 8 glasses * 240ml
  saturated_fat: 20,
  polyunsaturated_fat: 10,
  monounsaturated_fat: 25,
  trans_fat: 0,
  cholesterol: 300,
  sodium: 2300,
  potassium: 3500,
  dietary_fiber: 25,
  sugars: 50,
  vitamin_a: 900,
  vitamin_c: 90,
  calcium: 1000,
  iron: 18,
  target_exercise_calories_burned: 0,
  target_exercise_duration_minutes: 0,
  steps_goal: 10000,
  protein_percentage: null,
  carbs_percentage: null,
  fat_percentage: null,
  breakfast_percentage: 25,
  lunch_percentage: 25,
  dinner_percentage: 25,
  snacks_percentage: 25,
  custom_meal_percentages: {},
  custom_nutrients: {},
};
