/**
 * Canonical names of custom-measurement categories that the server auto-creates
 * from health integrations (HealthKit, Health Connect, Garmin, Oura, Fitbit,
 * Polar, Withings, Google Health/Health Connect, ...).
 *
 * Derivation (do not edit by hand without checking the server):
 *   - `SparkyFitnessServer/services/healthDataHandlers.ts`
 *     DEFAULT_UNITS_BY_HEALTH_TYPE keys (includes aggregated `_min`/`_max`/`_avg`
 *     variants) plus the hard-coded 'Stress' handler category;
 *   - `SparkyFitnessServer/services/garmin/garminHealthProcessor.ts`
 *     ('Raw Stress Data' — the Garmin mood/raw-JSON category);
 *   - `SparkyFitnessServer/integrations/{oura,fitbit,polar,withings,googlehealth}`
 *     hard-coded `categoryName` values.
 *
 * Matching semantics mirror server ingestion exactly: the server resolves a
 * category with `category.name === categoryName` (exact, case-sensitive), so
 * this set is matched the same way. A user who renames a synced category away
 * from its canonical name removes it from this heuristic and it behaves like a
 * normal category.
 *
 * PRESENTATION HEURISTIC (maintainer apedley, 2026-08): this set is NOT an
 * exclusion rule. In the Measurements Add screen, a matched Daily category
 * with no manual entry for the selected date is collapsed under the one-tap
 * "More categories" section so integration-heavy accounts stay compact, while
 * legitimate user collisions (e.g. `weight`, `Blood Pressure`) remain
 * accessible. A matched Daily category that ALREADY has a manual entry for the
 * selected date stays in the main custom list. The form/save model always
 * includes every Daily category, and every manual save uses `source: 'manual'`
 * (synced-only values are never prefilled as editable manual state). A
 * long-term server-side categorization flag remains future work.
 */
export const AUTO_HEALTH_SYNC_CUSTOM_CATEGORY_NAMES: ReadonlySet<string> = new Set([
  // ── healthDataHandlers DEFAULT_UNITS_BY_HEALTH_TYPE keys ────────────────
  'step',
  'steps',
  'heart_rate',
  'HeartRate',
  'Active Calories',
  'ActiveCaloriesBurned',
  'total_calories',
  'TotalCaloriesBurned',
  'distance',
  'Distance',
  'floors_climbed',
  'FloorsClimbed',
  'weight',
  'Weight',
  'sleep_session',
  'SleepSession',
  'stress',
  'Stress',
  'blood_pressure',
  'BloodPressure',
  'basal_metabolic_rate',
  'BasalMetabolicRate',
  'blood_glucose',
  'BloodGlucose',
  'body_fat',
  'BodyFat',
  'body_temperature',
  'BodyTemperature',
  'resting_heart_rate',
  'RestingHeartRate',
  'HRV',
  'HRV_SDNN',
  'respiratory_rate',
  'RespiratoryRate',
  'oxygen_saturation',
  'OxygenSaturation',
  'BloodOxygenSaturation',
  'vo2_max',
  'Vo2Max',
  'height',
  'Height',
  'neck',
  'waist',
  'hips',
  'hydration',
  'Hydration',
  'lean_body_mass',
  'LeanBodyMass',
  'basal_body_temperature',
  'BasalBodyTemperature',
  'elevation_gained',
  'ElevationGained',
  'bone_mass',
  'BoneMass',
  'speed',
  'Speed',
  'power',
  'Power',
  'steps_cadence',
  'StepsCadence',
  'cycling_pedaling_cadence',
  'CyclingPedalingCadence',
  'blood_alcohol_content',
  'BloodAlcoholContent',
  'nutrition',
  'Nutrition',
  // Aggregated min/max/avg variants
  'heart_rate_min',
  'heart_rate_max',
  'heart_rate_avg',
  'blood_glucose_min',
  'blood_glucose_max',
  'blood_glucose_avg',
  'blood_oxygen_saturation_min',
  'blood_oxygen_saturation_max',
  'blood_oxygen_saturation_avg',
  'respiratory_rate_min',
  'respiratory_rate_max',
  'respiratory_rate_avg',
  'HRV_min',
  'HRV_max',
  'HRV_avg',
  'HRV_SDNN_min',
  'HRV_SDNN_max',
  'HRV_SDNN_avg',
  'running_speed_min',
  'running_speed_max',
  'running_speed_avg',
  'running_power_min',
  'running_power_max',
  'running_power_avg',
  'running_stride_length_min',
  'running_stride_length_max',
  'running_stride_length_avg',
  'running_ground_contact_min',
  'running_ground_contact_max',
  'running_ground_contact_avg',
  'running_vertical_oscillation_min',
  'running_vertical_oscillation_max',
  'running_vertical_oscillation_avg',
  'cycling_speed_min',
  'cycling_speed_max',
  'cycling_speed_avg',
  'cycling_power_min',
  'cycling_power_max',
  'cycling_power_avg',
  'cycling_cadence_min',
  'cycling_cadence_max',
  'cycling_cadence_avg',
  'walking_speed_min',
  'walking_speed_max',
  'walking_speed_avg',
  'walking_step_length_min',
  'walking_step_length_max',
  'walking_step_length_avg',
  'walking_asymmetry_min',
  'walking_asymmetry_max',
  'walking_asymmetry_avg',
  'walking_double_support_min',
  'walking_double_support_max',
  'walking_double_support_avg',
  'steps_cadence_min',
  'steps_cadence_max',
  'steps_cadence_avg',
  'apple_move_time',
  'apple_exercise_time',
  'apple_stand_time',
  'dietary_fat_total',
  'dietary_protein',
  'dietary_sodium',
  'environmental_audio_exposure_min',
  'environmental_audio_exposure_max',
  'environmental_audio_exposure_avg',
  'headphone_audio_exposure_min',
  'headphone_audio_exposure_max',
  'headphone_audio_exposure_avg',
  'cycling_ftp',
  // ── Garmin ──────────────────────────────────────────────────────────────
  'Raw Stress Data',
  // ── Oura ────────────────────────────────────────────────────────────────
  'Metabolism',
  'Activity Score',
  'Readiness Score',
  'Skin Temperature Variation',
  'SpO2',
  'Breathing Disturbance Index',
  'Stress High Minutes',
  'Recovery High Minutes',
  'Vascular Age',
  'VO2 Max',
  'Heart Rate',
  // ── Fitbit ──────────────────────────────────────────────────────────────
  'Resting Heart Rate',
  'HRV',
  'Respiratory Rate',
  'Active Zone Minutes',
  'VO2 Max',
  'Core Temperature',
  // ── Polar ───────────────────────────────────────────────────────────────
  'Maximum Heart Rate',
  'Aerobic Threshold',
  'Anaerobic Threshold',
  'Steps',
  'Daily Calories',
  'Nightly Recharge Score',
  'ANS Charge',
  'Overnight HRV',
  'Overnight RHR',
  'Breathing Rate',
  // ── Withings ────────────────────────────────────────────────────────────
  'Fat Free Mass',
  'Fat Mass Weight',
  'Blood Pressure',
  'Body Temperature',
  'Blood Oxygen (SpO2)',
  'Skin Temperature',
  'Hydration',
  'Pulse Wave Velocity',
  'Heart Health',
  'ECG Metrics',
  'Body Water Breakdown',
  'Floors Climbed',
  'Nerve Health',
  'Segmental Body Comp',
  'Sleep Metrics',
  'Stress Metrics',
  'Visceral Fat',
  // ── Google Health / Health Connect ──────────────────────────────────────
  'Daily Calories',
  'Distance',
  'Floors',
  'Minutes Sedentary',
  'Minutes Lightly Active',
  'Minutes Fairly Active',
  'Minutes Very Active',
]);

/** Exact, case-sensitive match — mirrors server `category.name === categoryName`. */
export function isAutoHealthSyncCustomCategoryName(name: string): boolean {
  return AUTO_HEALTH_SYNC_CUSTOM_CATEGORY_NAMES.has(name);
}
