# Use an official Python runtime as a parent image
# FROM python:3.13.7-alpine3.22
FROM python:3.13.7-slim-trixie

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl openssl git \
    && rm -rf /var/lib/apt/lists/* \
    && update-ca-certificates

ENV REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Create the mock_data directory and set permissions for the 'daemon' user
RUN mkdir -p /app/mock_data && chown daemon:daemon /app/mock_data

# Expose the port that FastAPI will run on
EXPOSE 8000

USER daemon
# Run the FastAPI application using Uvicorn
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]