import { getClient } from '../db/poolManager.js';
import { log } from '../config/logging.js';

// User-scoped, provider-stamped entry tables that carry a `source` column.
// Every table here has ON DELETE CASCADE children (e.g. exercise_entry_sets,
// sleep_entry_stages, exercise_entries linked to a preset entry), so a single
// `DELETE ... WHERE user_id AND source` cleans up the whole subtree.
//
// See SYNCED_PROVIDER_TABLES below for the telemetry tables, which spell the
// same concept `source_provider`; SYNCED_TABLE_COLUMNS joins the two.
const SYNCED_SOURCE_TABLES = [
  'food_entries',
  'exercise_preset_entries',
  'exercise_entries',
  'sleep_entries',
  'custom_measurements',
  'water_intake',
  'water_intake_entries',
] as const;

// Wearable telemetry tables. Identical purpose to the list above, but they spell
// the provenance column `source_provider` rather than `source`, so they need
// their own list and cannot simply be appended to SYNCED_SOURCE_TABLES.
//
// Without these, deleting a provider left orphans behind: the wellness tables
// reference exercise/sleep entries with ON DELETE SET NULL (not CASCADE), so
// removing the diary rows only nulled the links and the readings themselves
// survived. daily_health_metrics has no FK to anything and survived outright.
//
// NOTE: exercise_entry_gps_points / _laps / _hr_zones are deliberately absent —
// they carry no provenance column and already CASCADE from exercise_entries.
const SYNCED_PROVIDER_TABLES = [
  'health_metric_samples',
  'vitals_entries',
  'daily_health_metrics',
] as const;

type SyncedSourceTable =
  | (typeof SYNCED_SOURCE_TABLES)[number]
  | (typeof SYNCED_PROVIDER_TABLES)[number];

// Every synced table paired with the column holding its provider name. Both the
// table and column identifiers are interpolated into SQL below, so this must
// stay a hardcoded whitelist — never widen it with caller-provided input.
//
// Order is significant: exercise_preset_entries must precede exercise_entries so
// preset sessions and their cascade-linked child entries are removed first.
const SYNCED_TABLE_COLUMNS: ReadonlyArray<
  readonly [SyncedSourceTable, 'source' | 'source_provider']
> = [
  ...SYNCED_SOURCE_TABLES.map((t) => [t, 'source'] as const),
  ...SYNCED_PROVIDER_TABLES.map((t) => [t, 'source_provider'] as const),
];

// Source values that represent data the USER created themselves (not synced or
// imported from an external provider), and so must never be surfaced or deleted
// by this by-source cleanup tool:
//   - 'manual'          : typed in from web/mobile (most tables)
//   - 'sparky'          : logged via the Sparky AI assistant / chatbot
//   - 'workout preset'  : workout logged from a saved preset (exercise entries)
//   - 'workout plan'    : diary entries generated by a scheduled workout plan
// NOTE: the app is inconsistent about casing — exercise_entries default to
// 'Manual' (capital M), and the preset/plan values are Title Case, while other
// tables use lowercase 'manual'. So every comparison is done case-insensitively
// (LOWER(source) in SQL, toLowerCase() in JS). This is a denylist: if a NEW
// user-originated source tag is ever introduced in the app, add it here so it
// is not offered for deletion.
const USER_ORIGINATED_SOURCES = [
  'manual',
  'sparky',
  'workout preset',
  'workout plan',
] as const;

// True when a source string represents user-created data, regardless of casing.
const isUserOriginatedSource = (source: string | null | undefined): boolean =>
  USER_ORIGINATED_SOURCES.includes(
    (source ?? '')
      .trim()
      .toLowerCase() as (typeof USER_ORIGINATED_SOURCES)[number]
  );

export interface SyncedSourceSummary {
  source: string;
  totalCount: number;
  byTable: Partial<Record<SyncedSourceTable, number>>;
}

// Returns one entry per distinct provider `source` the user has synced data
// for, with a per-table breakdown of how many rows carry that source.
// User-originated sources (manual / workout preset / workout plan) and NULL are
// excluded so this can never surface — or later delete — data the user created
// themselves.
async function getSyncedSourceSummary(
  userId: string
): Promise<SyncedSourceSummary[]> {
  const client = await getClient(userId);
  try {
    const summary = new Map<string, SyncedSourceSummary>();
    for (const [table, column] of SYNCED_TABLE_COLUMNS) {
      const result = await client.query(
        `SELECT ${column} AS source, COUNT(*)::int AS count
           FROM ${table}
          WHERE user_id = $1
            AND ${column} IS NOT NULL
            AND LOWER(${column}) <> ALL($2::text[])
          GROUP BY ${column}`,
        [userId, USER_ORIGINATED_SOURCES]
      );
      for (const row of result.rows) {
        const source: string = row.source;
        const count: number = row.count;
        const existing = summary.get(source) ?? {
          source,
          totalCount: 0,
          byTable: {},
        };
        existing.totalCount += count;
        existing.byTable[table] = count;
        summary.set(source, existing);
      }
    }
    return Array.from(summary.values()).sort(
      (a, b) => b.totalCount - a.totalCount
    );
  } finally {
    client.release();
  }
}

// Deletes every row across the synced entry tables that carries the given
// `source`, for this user only, in a single transaction. Refuses any
// user-originated source (manual / workout preset / workout plan). Returns the
// per-table deleted-row counts.
async function deleteSyncedDataBySource(
  userId: string,
  source: string
): Promise<{ byTable: Record<string, number>; totalDeleted: number }> {
  if (isUserOriginatedSource(source)) {
    throw new Error(
      `Refusing to bulk-delete user-created data (source '${source}').`
    );
  }
  const client = await getClient(userId);
  try {
    await client.query('BEGIN');
    const byTable: Record<string, number> = {};
    let totalDeleted = 0;
    for (const [table, column] of SYNCED_TABLE_COLUMNS) {
      const result = await client.query(
        `DELETE FROM ${table} WHERE user_id = $1 AND ${column} = $2`,
        [userId, source]
      );
      const deleted = result.rowCount ?? 0;
      byTable[table] = deleted;
      totalDeleted += deleted;
    }
    await client.query('COMMIT');
    log(
      'info',
      `[syncedData] Deleted ${totalDeleted} synced rows with source '${source}' for user ${userId}.`,
      byTable
    );
    return { byTable, totalDeleted };
  } catch (error) {
    await client.query('ROLLBACK');
    log(
      'error',
      `[syncedData] Error deleting synced data for source '${source}', user ${userId}:`,
      error
    );
    throw error;
  } finally {
    client.release();
  }
}

export {
  SYNCED_SOURCE_TABLES,
  SYNCED_PROVIDER_TABLES,
  SYNCED_TABLE_COLUMNS,
  USER_ORIGINATED_SOURCES,
  isUserOriginatedSource,
  getSyncedSourceSummary,
  deleteSyncedDataBySource,
};
