// Generated by ts-to-zod
import { z } from "zod";
import {
  aiServiceSettingsInitializerSchema,
  aiServiceSettingsMutatorSchema,
  aiServiceSettingsSchema,
} from "../database/AiServiceSettings.zod.ts";

export const aiServiceSettingsResponseSchema = aiServiceSettingsSchema
  .extend({
    source: z.string().optional(),
    creator_name: z.string().nullable().optional(),
  })
  .omit({
    encrypted_api_key: true,
    api_key_iv: true,
    api_key_tag: true,
  });

export const aiServiceSettingsPostResponseSchema = z.object({
  message: z.string(),
  setting: aiServiceSettingsResponseSchema,
});

export const createAiServiceSettingsRequestSchema =
  aiServiceSettingsInitializerSchema
    .pick({
      chat_tool_profile: true,
      custom_url: true,
      is_active: true,
      model_name: true,
      service_name: true,
      service_type: true,
      system_prompt: true,
    })
    .extend({
      api_key: z.string().optional(),
    });

export const updateAiServiceSettingsRequestSchema =
  aiServiceSettingsMutatorSchema
    .pick({
      chat_tool_profile: true,
      custom_url: true,
      id: true,
      is_active: true,
      is_public: true,
      model_name: true,
      service_name: true,
      service_type: true,
      system_prompt: true,
    })
    .extend({
      api_key: z.string().optional(),
    });
export type AiServiceSettingsResponse = z.infer<
  typeof aiServiceSettingsResponseSchema
>;
export type CreateAiServiceSettingsRequest = z.infer<
  typeof createAiServiceSettingsRequestSchema
>;
export type UpdateAiServiceSettingsRequest = z.infer<
  typeof updateAiServiceSettingsRequestSchema
>;

export type AiServiceSettingsPostResponse = z.infer<
  typeof aiServiceSettingsPostResponseSchema
>;
