import { z } from "zod";

export const dailyHealthMetricsIdSchema = z.string();

export const dailyHealthMetricsSchema = z.object({
  id: dailyHealthMetricsIdSchema,
  user_id: z.string(),
  entry_date: z.string(),
  source_provider: z.string(),
  device_name: z.string().nullable(),
  total_steps: z.number().nullable(),
  step_goal: z.number().nullable(),
  total_distance_meters: z.number().nullable(),
  floors_ascended: z.number().nullable(),
  floors_descended: z.number().nullable(),
  active_calories: z.number().nullable(),
  bmr_calories: z.number().nullable(),
  total_calories: z.number().nullable(),
  highly_active_seconds: z.number().nullable(),
  active_seconds: z.number().nullable(),
  sedentary_seconds: z.number().nullable(),
  moderate_intensity_minutes: z.number().nullable(),
  vigorous_intensity_minutes: z.number().nullable(),
  exercise_minutes: z.number().nullable(),
  stand_hours: z.number().nullable(),
  resting_heart_rate: z.number().nullable(),
  heart_rate_recovery_1min: z.number().nullable(),
  vo2_max: z.number().nullable(),
  fitness_age: z.number().nullable(),
  lactate_threshold_bpm: z.number().nullable(),
  lactate_threshold_speed_mps: z.number().nullable(),
  walking_asymmetry_percentage: z.number().nullable(),
  hill_score: z.number().nullable(),
  race_prediction_5k_seconds: z.number().nullable(),
  race_prediction_10k_seconds: z.number().nullable(),
  race_prediction_half_marathon_seconds: z.number().nullable(),
  race_prediction_marathon_seconds: z.number().nullable(),
  recovery_time_hours: z.number().nullable(),
  training_readiness_score: z.number().nullable(),
  endurance_score: z.number().nullable(),
  weekly_training_load: z.number().nullable(),
  acute_training_load: z.number().nullable(),
  chronic_training_load: z.number().nullable(),
  acwr_ratio: z.number().nullable(),
  avg_stress_level: z.number().nullable(),
  max_stress_level: z.number().nullable(),
  body_battery_charged: z.number().nullable(),
  body_battery_drained: z.number().nullable(),
  body_battery_highest: z.number().nullable(),
  body_battery_lowest: z.number().nullable(),
  created_at: z.coerce.date().nullable(),
  updated_at: z.coerce.date().nullable(),
});

export const dailyHealthMetricsInitializerSchema = z.object({
  id: dailyHealthMetricsIdSchema.optional(),
  user_id: z.string(),
  entry_date: z.string(),
  source_provider: z.string(),
  device_name: z.string().optional().nullable(),
  total_steps: z.number().optional().nullable(),
  step_goal: z.number().optional().nullable(),
  total_distance_meters: z.number().optional().nullable(),
  floors_ascended: z.number().optional().nullable(),
  floors_descended: z.number().optional().nullable(),
  active_calories: z.number().optional().nullable(),
  bmr_calories: z.number().optional().nullable(),
  total_calories: z.number().optional().nullable(),
  highly_active_seconds: z.number().optional().nullable(),
  active_seconds: z.number().optional().nullable(),
  sedentary_seconds: z.number().optional().nullable(),
  moderate_intensity_minutes: z.number().optional().nullable(),
  vigorous_intensity_minutes: z.number().optional().nullable(),
  exercise_minutes: z.number().optional().nullable(),
  stand_hours: z.number().optional().nullable(),
  resting_heart_rate: z.number().optional().nullable(),
  heart_rate_recovery_1min: z.number().optional().nullable(),
  vo2_max: z.number().optional().nullable(),
  fitness_age: z.number().optional().nullable(),
  lactate_threshold_bpm: z.number().optional().nullable(),
  lactate_threshold_speed_mps: z.number().optional().nullable(),
  walking_asymmetry_percentage: z.number().optional().nullable(),
  hill_score: z.number().optional().nullable(),
  race_prediction_5k_seconds: z.number().optional().nullable(),
  race_prediction_10k_seconds: z.number().optional().nullable(),
  race_prediction_half_marathon_seconds: z.number().optional().nullable(),
  race_prediction_marathon_seconds: z.number().optional().nullable(),
  recovery_time_hours: z.number().optional().nullable(),
  training_readiness_score: z.number().optional().nullable(),
  endurance_score: z.number().optional().nullable(),
  weekly_training_load: z.number().optional().nullable(),
  acute_training_load: z.number().optional().nullable(),
  chronic_training_load: z.number().optional().nullable(),
  acwr_ratio: z.number().optional().nullable(),
  avg_stress_level: z.number().optional().nullable(),
  max_stress_level: z.number().optional().nullable(),
  body_battery_charged: z.number().optional().nullable(),
  body_battery_drained: z.number().optional().nullable(),
  body_battery_highest: z.number().optional().nullable(),
  body_battery_lowest: z.number().optional().nullable(),
  created_at: z.coerce.date().optional().nullable(),
  updated_at: z.coerce.date().optional().nullable(),
});

export const dailyHealthMetricsMutatorSchema = dailyHealthMetricsInitializerSchema.partial();

export type DailyHealthMetrics = z.infer<typeof dailyHealthMetricsSchema>;
export type DailyHealthMetricsInitializer = z.infer<typeof dailyHealthMetricsInitializerSchema>;
export type DailyHealthMetricsMutator = z.infer<typeof dailyHealthMetricsMutatorSchema>;
