// Generated by ts-to-zod
import { z } from "zod";

export const exerciseEntriesIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.exercise_entries"),
  }),
);

const exercisesIdSchema = z.any();

const workoutPlanTemplateAssignmentsIdSchema = z.any();

const userIdSchema = z.any();

const exercisePresetEntriesIdSchema = z.any();

export const exerciseEntriesSchema = z.object({
  id: exerciseEntriesIdSchema,
  user_id: z.string(),
  exercise_id: exercisesIdSchema,
  duration_minutes: z.number(),
  calories_burned: z.number(),
  entry_date: z.date().nullable(),
  notes: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date(),
  workout_plan_assignment_id: workoutPlanTemplateAssignmentsIdSchema.nullable(),
  image_url: z.string().nullable(),
  created_by_user_id: userIdSchema.nullable(),
  exercise_name: z.string().nullable(),
  calories_per_hour: z.number().nullable(),
  updated_by_user_id: userIdSchema.nullable(),
  category: z.string().nullable(),
  source: z.string().nullable(),
  source_id: z.string().nullable(),
  force: z.string().nullable(),
  level: z.string().nullable(),
  mechanic: z.string().nullable(),
  equipment: z.string().nullable(),
  primary_muscles: z.string().nullable(),
  secondary_muscles: z.string().nullable(),
  instructions: z.string().nullable(),
  images: z.string().nullable(),
  distance: z.number().nullable(),
  avg_heart_rate: z.number().nullable(),
  exercise_preset_entry_id: exercisePresetEntriesIdSchema.nullable(),
  sort_order: z.number().nullable(),
});

export const exerciseEntriesInitializerSchema = z.object({
  id: exerciseEntriesIdSchema.optional(),
  user_id: z.string(),
  exercise_id: exercisesIdSchema,
  duration_minutes: z.number(),
  calories_burned: z.number(),
  entry_date: z.date().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional(),
  workout_plan_assignment_id: workoutPlanTemplateAssignmentsIdSchema
    .optional()
    .nullable(),
  image_url: z.string().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  exercise_name: z.string().optional().nullable(),
  calories_per_hour: z.number().optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
  category: z.string().optional().nullable(),
  source: z.string().optional().nullable(),
  source_id: z.string().optional().nullable(),
  force: z.string().optional().nullable(),
  level: z.string().optional().nullable(),
  mechanic: z.string().optional().nullable(),
  equipment: z.string().optional().nullable(),
  primary_muscles: z.string().optional().nullable(),
  secondary_muscles: z.string().optional().nullable(),
  instructions: z.string().optional().nullable(),
  images: z.string().optional().nullable(),
  distance: z.number().optional().nullable(),
  avg_heart_rate: z.number().optional().nullable(),
  exercise_preset_entry_id: exercisePresetEntriesIdSchema.optional().nullable(),
  sort_order: z.number().optional().nullable(),
});

export const exerciseEntriesMutatorSchema = z.object({
  id: exerciseEntriesIdSchema.optional(),
  user_id: z.string().optional(),
  exercise_id: exercisesIdSchema.optional(),
  duration_minutes: z.number().optional(),
  calories_burned: z.number().optional(),
  entry_date: z.date().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional(),
  workout_plan_assignment_id: workoutPlanTemplateAssignmentsIdSchema
    .optional()
    .nullable(),
  image_url: z.string().optional().nullable(),
  created_by_user_id: userIdSchema.optional().nullable(),
  exercise_name: z.string().optional().nullable(),
  calories_per_hour: z.number().optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
  category: z.string().optional().nullable(),
  source: z.string().optional().nullable(),
  source_id: z.string().optional().nullable(),
  force: z.string().optional().nullable(),
  level: z.string().optional().nullable(),
  mechanic: z.string().optional().nullable(),
  equipment: z.string().optional().nullable(),
  primary_muscles: z.string().optional().nullable(),
  secondary_muscles: z.string().optional().nullable(),
  instructions: z.string().optional().nullable(),
  images: z.string().optional().nullable(),
  distance: z.number().optional().nullable(),
  avg_heart_rate: z.number().optional().nullable(),
  exercise_preset_entry_id: exercisePresetEntriesIdSchema.optional().nullable(),
  sort_order: z.number().optional().nullable(),
});

export type ExerciseEntries = z.infer<typeof exerciseEntriesSchema>;
export type ExerciseEntriesInitializer = z.infer<typeof exerciseEntriesInitializerSchema>;
export type ExerciseEntriesMutator = z.infer<typeof exerciseEntriesMutatorSchema>;
