import { z } from "zod";

export const exerciseEntriesIdSchema = z.string();

export const exerciseEntriesSchema = z.object({
  id: exerciseEntriesIdSchema,
  user_id: z.string(),
  exercise_id: z.string(),
  duration_minutes: z.number(),
  calories_burned: z.number(),
  entry_date: z.date().nullable(),
  entry_time: z.string().nullable(),
  notes: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date(),
  workout_plan_assignment_id: z.string().nullable(),
  image_url: z.string().nullable(),
  created_by_user_id: z.string().nullable(),
  exercise_name: z.string().nullable(),
  calories_per_hour: z.number().nullable(),
  updated_by_user_id: z.string().nullable(),
  category: z.string().nullable(),
  source: z.string().nullable(),
  source_id: z.string().nullable(),
  force: z.string().nullable(),
  level: z.string().nullable(),
  mechanic: z.string().nullable(),
  equipment: z.string().nullable(),
  primary_muscles: z.string().nullable(),
  secondary_muscles: z.string().nullable(),
  instructions: z.string().nullable(),
  images: z.string().nullable(),
  distance: z.number().nullable(),
  avg_heart_rate: z.number().nullable(),
  exercise_preset_entry_id: z.string().nullable(),
  sort_order: z.number().nullable(),
  superset_group: z.number().nullable(),
  modality: z.string().nullable(),
  // New telemetry fields
  max_heart_rate: z.number().nullable(),
  heart_rate_recovery_1min: z.number().nullable(),
  avg_respiration_brpm: z.number().nullable(),
  max_respiration_brpm: z.number().nullable(),
  avg_speed_mps: z.number().nullable(),
  max_speed_mps: z.number().nullable(),
  avg_cadence: z.number().nullable(),
  max_cadence: z.number().nullable(),
  avg_power_watts: z.number().nullable(),
  max_power_watts: z.number().nullable(),
  normalized_power_watts: z.number().nullable(),
  tss_score: z.number().nullable(),
  intensity_factor: z.number().nullable(),
  ground_contact_time_ms: z.number().nullable(),
  vertical_oscillation_mm: z.number().nullable(),
  stride_length_cm: z.number().nullable(),
  avg_temperature_celsius: z.number().nullable(),
  max_temperature_celsius: z.number().nullable(),
  elevation_gain_meters: z.number().nullable(),
  elevation_loss_meters: z.number().nullable(),
  floors_climbed: z.number().nullable(),
  stroke_count: z.number().nullable(),
  training_load: z.number().nullable(),
  aerobic_training_effect: z.number().nullable(),
  anaerobic_training_effect: z.number().nullable(),
  vo2_max_estimate: z.number().nullable(),
  // Garmin-parity fields added 2026-07-31
  moving_time_seconds: z.number().nullable(),
  elapsed_time_seconds: z.number().nullable(),
  work_time_seconds: z.number().nullable(),
  resting_calories: z.number().nullable(),
  active_calories: z.number().nullable(),
  avg_moving_speed_mps: z.number().nullable(),
  min_elevation_meters: z.number().nullable(),
  max_elevation_meters: z.number().nullable(),
  weather_temp_celsius: z.number().nullable(),
  weather_condition: z.string().nullable(),
  weather_wind_speed_mps: z.number().nullable(),
  weather_humidity_percentage: z.number().nullable(),
  gear_name: z.string().nullable(),
  gear_external_id: z.string().nullable(),
});

export const exerciseEntriesInitializerSchema = z.object({
  id: exerciseEntriesIdSchema.optional(),
  user_id: z.string(),
  exercise_id: z.string(),
  duration_minutes: z.number(),
  calories_burned: z.number(),
  entry_date: z.date().optional().nullable(),
  entry_time: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional(),
  workout_plan_assignment_id: z.string().optional().nullable(),
  image_url: z.string().optional().nullable(),
  created_by_user_id: z.string().optional().nullable(),
  exercise_name: z.string().optional().nullable(),
  calories_per_hour: z.number().optional().nullable(),
  updated_by_user_id: z.string().optional().nullable(),
  category: z.string().optional().nullable(),
  source: z.string().optional().nullable(),
  source_id: z.string().optional().nullable(),
  force: z.string().optional().nullable(),
  level: z.string().optional().nullable(),
  mechanic: z.string().optional().nullable(),
  equipment: z.string().optional().nullable(),
  primary_muscles: z.string().optional().nullable(),
  secondary_muscles: z.string().optional().nullable(),
  instructions: z.string().optional().nullable(),
  images: z.string().optional().nullable(),
  distance: z.number().optional().nullable(),
  avg_heart_rate: z.number().optional().nullable(),
  exercise_preset_entry_id: z.string().optional().nullable(),
  sort_order: z.number().optional().nullable(),
  superset_group: z.number().optional().nullable(),
  modality: z.string().optional().nullable(),
  max_heart_rate: z.number().optional().nullable(),
  heart_rate_recovery_1min: z.number().optional().nullable(),
  avg_respiration_brpm: z.number().optional().nullable(),
  max_respiration_brpm: z.number().optional().nullable(),
  avg_speed_mps: z.number().optional().nullable(),
  max_speed_mps: z.number().optional().nullable(),
  avg_cadence: z.number().optional().nullable(),
  max_cadence: z.number().optional().nullable(),
  avg_power_watts: z.number().optional().nullable(),
  max_power_watts: z.number().optional().nullable(),
  normalized_power_watts: z.number().optional().nullable(),
  tss_score: z.number().optional().nullable(),
  intensity_factor: z.number().optional().nullable(),
  ground_contact_time_ms: z.number().optional().nullable(),
  vertical_oscillation_mm: z.number().optional().nullable(),
  stride_length_cm: z.number().optional().nullable(),
  avg_temperature_celsius: z.number().optional().nullable(),
  max_temperature_celsius: z.number().optional().nullable(),
  elevation_gain_meters: z.number().optional().nullable(),
  elevation_loss_meters: z.number().optional().nullable(),
  floors_climbed: z.number().optional().nullable(),
  stroke_count: z.number().optional().nullable(),
  training_load: z.number().optional().nullable(),
  aerobic_training_effect: z.number().optional().nullable(),
  anaerobic_training_effect: z.number().optional().nullable(),
  vo2_max_estimate: z.number().optional().nullable(),
  moving_time_seconds: z.number().optional().nullable(),
  elapsed_time_seconds: z.number().optional().nullable(),
  work_time_seconds: z.number().optional().nullable(),
  resting_calories: z.number().optional().nullable(),
  active_calories: z.number().optional().nullable(),
  avg_moving_speed_mps: z.number().optional().nullable(),
  min_elevation_meters: z.number().optional().nullable(),
  max_elevation_meters: z.number().optional().nullable(),
  weather_temp_celsius: z.number().optional().nullable(),
  weather_condition: z.string().optional().nullable(),
  weather_wind_speed_mps: z.number().optional().nullable(),
  weather_humidity_percentage: z.number().optional().nullable(),
  gear_name: z.string().optional().nullable(),
  gear_external_id: z.string().optional().nullable(),
});

export const exerciseEntriesMutatorSchema = exerciseEntriesInitializerSchema.partial();

export type ExerciseEntries = z.infer<typeof exerciseEntriesSchema>;
export type ExerciseEntriesInitializer = z.infer<typeof exerciseEntriesInitializerSchema>;
export type ExerciseEntriesMutator = z.infer<typeof exerciseEntriesMutatorSchema>;
