// Generated by ts-to-zod
import { z } from "zod";

export const exercisesIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.exercises"),
  }),
);

export const exercisesSchema = z.object({
  id: exercisesIdSchema,
  name: z.string(),
  category: z.string().nullable(),
  calories_per_hour: z.number().nullable(),
  description: z.string().nullable(),
  user_id: z.string().nullable(),
  is_custom: z.boolean().nullable(),
  shared_with_public: z.boolean().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  source_external_id: z.string().nullable(),
  source: z.string(),
  source_id: z.string().nullable(),
  force: z.string().nullable(),
  level: z.string().nullable(),
  mechanic: z.string().nullable(),
  equipment: z.string().nullable(),
  primary_muscles: z.string().nullable(),
  secondary_muscles: z.string().nullable(),
  instructions: z.string().nullable(),
  images: z.string().nullable(),
  is_quick_exercise: z.boolean().nullable(),
});

export const exercisesInitializerSchema = z.object({
  id: exercisesIdSchema.optional(),
  name: z.string(),
  category: z.string().optional().nullable(),
  calories_per_hour: z.number().optional().nullable(),
  description: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
  is_custom: z.boolean().optional().nullable(),
  shared_with_public: z.boolean().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  source_external_id: z.string().optional().nullable(),
  source: z.string(),
  source_id: z.string().optional().nullable(),
  force: z.string().optional().nullable(),
  level: z.string().optional().nullable(),
  mechanic: z.string().optional().nullable(),
  equipment: z.string().optional().nullable(),
  primary_muscles: z.string().optional().nullable(),
  secondary_muscles: z.string().optional().nullable(),
  instructions: z.string().optional().nullable(),
  images: z.string().optional().nullable(),
  is_quick_exercise: z.boolean().optional().nullable(),
});

export const exercisesMutatorSchema = z.object({
  id: exercisesIdSchema.optional(),
  name: z.string().optional(),
  category: z.string().optional().nullable(),
  calories_per_hour: z.number().optional().nullable(),
  description: z.string().optional().nullable(),
  user_id: z.string().optional().nullable(),
  is_custom: z.boolean().optional().nullable(),
  shared_with_public: z.boolean().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  source_external_id: z.string().optional().nullable(),
  source: z.string().optional(),
  source_id: z.string().optional().nullable(),
  force: z.string().optional().nullable(),
  level: z.string().optional().nullable(),
  mechanic: z.string().optional().nullable(),
  equipment: z.string().optional().nullable(),
  primary_muscles: z.string().optional().nullable(),
  secondary_muscles: z.string().optional().nullable(),
  instructions: z.string().optional().nullable(),
  images: z.string().optional().nullable(),
  is_quick_exercise: z.boolean().optional().nullable(),
});

export type Exercises = z.infer<typeof exercisesSchema>;
export type ExercisesInitializer = z.infer<typeof exercisesInitializerSchema>;
export type ExercisesMutator = z.infer<typeof exercisesMutatorSchema>;
