// Generated by ts-to-zod
import { z } from "zod";

export const exerciseEntrySetsIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.exercise_entry_sets"),
  }),
);

const exerciseEntriesIdSchema = z.any();

export const exerciseEntrySetsSchema = z.object({
  id: exerciseEntrySetsIdSchema,
  exercise_entry_id: exerciseEntriesIdSchema,
  set_number: z.number(),
  set_type: z.string().nullable(),
  reps: z.number().nullable(),
  weight: z.number().nullable(),
  duration: z.number().nullable(),
  rest_time: z.number().nullable(),
  notes: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  rpe: z.number().nullable(),
});

export const exerciseEntrySetsInitializerSchema = z.object({
  id: exerciseEntrySetsIdSchema.optional(),
  exercise_entry_id: exerciseEntriesIdSchema,
  set_number: z.number(),
  set_type: z.string().optional().nullable(),
  reps: z.number().optional().nullable(),
  weight: z.number().optional().nullable(),
  duration: z.number().optional().nullable(),
  rest_time: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  rpe: z.number().optional().nullable(),
});

export const exerciseEntrySetsMutatorSchema = z.object({
  id: exerciseEntrySetsIdSchema.optional(),
  exercise_entry_id: exerciseEntriesIdSchema.optional(),
  set_number: z.number().optional(),
  set_type: z.string().optional().nullable(),
  reps: z.number().optional().nullable(),
  weight: z.number().optional().nullable(),
  duration: z.number().optional().nullable(),
  rest_time: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  rpe: z.number().optional().nullable(),
});

export type ExerciseEntrySets = z.infer<typeof exerciseEntrySetsSchema>;
export type ExerciseEntrySetsInitializer = z.infer<typeof exerciseEntrySetsInitializerSchema>;
export type ExerciseEntrySetsMutator = z.infer<typeof exerciseEntrySetsMutatorSchema>;
