// Generated by ts-to-zod
import { z } from "zod";

export const externalProviderTypesIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.external_provider_types"),
  }),
);

export const externalProviderTypesSchema = z.object({
  id: externalProviderTypesIdSchema,
  display_name: z.string(),
  description: z.string().nullable(),
  created_at: z.date().nullable(),
  is_strictly_private: z.boolean().nullable(),
  categories: z.array(z.string()).nullable().optional(),
  required_fields: z.array(z.string()).nullable().optional(),
  field_labels: z.record(z.string(), z.string()).nullable().optional(),
  supports_barcode: z.boolean().nullable().optional(),
});

export const externalProviderTypesInitializerSchema = z.object({
  id: externalProviderTypesIdSchema,
  display_name: z.string(),
  description: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  is_strictly_private: z.boolean().optional().nullable(),
  categories: z.array(z.string()).optional().nullable(),
  required_fields: z.array(z.string()).optional().nullable(),
  field_labels: z.record(z.string(), z.string()).optional().nullable(),
  supports_barcode: z.boolean().optional().nullable(),
});

export const externalProviderTypesMutatorSchema = z.object({
  id: externalProviderTypesIdSchema.optional(),
  display_name: z.string().optional(),
  description: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  is_strictly_private: z.boolean().optional().nullable(),
  categories: z.array(z.string()).optional().nullable(),
  required_fields: z.array(z.string()).optional().nullable(),
  field_labels: z.record(z.string(), z.string()).optional().nullable(),
  supports_barcode: z.boolean().optional().nullable(),
});

export type ExternalProviderTypes = z.infer<typeof externalProviderTypesSchema>;
export type ExternalProviderTypesInitializer = z.infer<typeof externalProviderTypesInitializerSchema>;
export type ExternalProviderTypesMutator = z.infer<typeof externalProviderTypesMutatorSchema>;
