// Generated by ts-to-zod
import { z } from "zod";

export const foodEntryMealsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.food_entry_meals"),
  }),
);

const userIdSchema = z.any();

const mealsIdSchema = z.any();

const mealTypesIdSchema = z.any();

export const foodEntryMealsSchema = z.object({
  id: foodEntryMealsIdSchema,
  user_id: userIdSchema,
  meal_template_id: mealsIdSchema.nullable(),
  entry_date: z.date(),
  name: z.string(),
  description: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  created_by_user_id: userIdSchema,
  updated_by_user_id: userIdSchema,
  quantity: z.number(),
  unit: z.string().nullable(),
  meal_type_id: mealTypesIdSchema,
  legacy_serving_unit_math: z.boolean(),
});

export const foodEntryMealsInitializerSchema = z.object({
  id: foodEntryMealsIdSchema.optional(),
  user_id: userIdSchema,
  meal_template_id: mealsIdSchema.optional().nullable(),
  entry_date: z.date(),
  name: z.string(),
  description: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  created_by_user_id: userIdSchema,
  updated_by_user_id: userIdSchema,
  quantity: z.number().optional(),
  unit: z.string().optional().nullable(),
  meal_type_id: mealTypesIdSchema,
  legacy_serving_unit_math: z.boolean().optional(),
});

export const foodEntryMealsMutatorSchema = z.object({
  id: foodEntryMealsIdSchema.optional(),
  user_id: userIdSchema.optional(),
  meal_template_id: mealsIdSchema.optional().nullable(),
  entry_date: z.date().optional(),
  name: z.string().optional(),
  description: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  created_by_user_id: userIdSchema.optional(),
  updated_by_user_id: userIdSchema.optional(),
  quantity: z.number().optional(),
  unit: z.string().optional().nullable(),
  meal_type_id: mealTypesIdSchema.optional(),
  legacy_serving_unit_math: z.boolean().optional(),
});

export type FoodEntryMeals = z.infer<typeof foodEntryMealsSchema>;
export type FoodEntryMealsInitializer = z.infer<typeof foodEntryMealsInitializerSchema>;
export type FoodEntryMealsMutator = z.infer<typeof foodEntryMealsMutatorSchema>;
