// Generated by ts-to-zod
import { z } from "zod";

export const foodFavoritesIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.food_favorites"),
  }),
);

const userIdSchema = z.any();

const foodsIdSchema = z.any();

const mealsIdSchema = z.any();

export const foodFavoritesSchema = z.object({
  id: foodFavoritesIdSchema,
  user_id: userIdSchema,
  food_id: foodsIdSchema.nullable(),
  meal_id: mealsIdSchema.nullable(),
  created_at: z.date().nullable(),
});

export const foodFavoritesInitializerSchema = z.object({
  id: foodFavoritesIdSchema.optional(),
  user_id: userIdSchema,
  food_id: foodsIdSchema.optional().nullable(),
  meal_id: mealsIdSchema.optional().nullable(),
  created_at: z.date().optional().nullable(),
});

export const foodFavoritesMutatorSchema = z.object({
  id: foodFavoritesIdSchema.optional(),
  user_id: userIdSchema.optional(),
  food_id: foodsIdSchema.optional().nullable(),
  meal_id: mealsIdSchema.optional().nullable(),
  created_at: z.date().optional().nullable(),
});

export type FoodFavorites = z.infer<typeof foodFavoritesSchema>;
export type FoodFavoritesInitializer = z.infer<
  typeof foodFavoritesInitializerSchema
>;
export type FoodFavoritesMutator = z.infer<typeof foodFavoritesMutatorSchema>;
