// Generated by ts-to-zod
import { z } from "zod";

export const foodsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.foods"),
  }),
);

export const foodsSchema = z.object({
  id: foodsIdSchema,
  user_id: z.string().nullable(),
  name: z.string(),
  brand: z.string().nullable(),
  barcode: z.string().nullable(),
  provider_external_id: z.string().nullable(),
  is_custom: z.boolean().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  shared_with_public: z.boolean().nullable(),
  provider_type: z.string().nullable(),
  is_quick_food: z.boolean(),
});

export const foodsInitializerSchema = z.object({
  id: foodsIdSchema.optional(),
  user_id: z.string().optional().nullable(),
  name: z.string(),
  brand: z.string().optional().nullable(),
  barcode: z.string().optional().nullable(),
  provider_external_id: z.string().optional().nullable(),
  is_custom: z.boolean().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  shared_with_public: z.boolean().optional().nullable(),
  provider_type: z.string().optional().nullable(),
  is_quick_food: z.boolean().optional(),
});

export const foodsMutatorSchema = z.object({
  id: foodsIdSchema.optional(),
  user_id: z.string().optional().nullable(),
  name: z.string().optional(),
  brand: z.string().optional().nullable(),
  barcode: z.string().optional().nullable(),
  provider_external_id: z.string().optional().nullable(),
  is_custom: z.boolean().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  shared_with_public: z.boolean().optional().nullable(),
  provider_type: z.string().optional().nullable(),
  is_quick_food: z.boolean().optional(),
});

export type Foods = z.infer<typeof foodsSchema>;
export type FoodsInitializer = z.infer<typeof foodsInitializerSchema>;
export type FoodsMutator = z.infer<typeof foodsMutatorSchema>;
