// Generated by ts-to-zod
import { z } from "zod";

export const globalSettingsIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.global_settings"),
  }),
);

export const globalSettingsSchema = z.object({
  id: globalSettingsIdSchema,
  enable_email_password_login: z.boolean(),
  is_oidc_active: z.boolean(),
  updated_at: z.date().nullable(),
  mfa_mandatory: z.boolean().nullable(),
  allow_user_ai_config: z.boolean(),
});

export const globalSettingsInitializerSchema = z.object({
  id: globalSettingsIdSchema.optional(),
  enable_email_password_login: z.boolean().optional(),
  is_oidc_active: z.boolean().optional(),
  updated_at: z.date().optional().nullable(),
  mfa_mandatory: z.boolean().optional().nullable(),
  allow_user_ai_config: z.boolean().optional(),
});

export const globalSettingsMutatorSchema = z.object({
  id: globalSettingsIdSchema.optional(),
  enable_email_password_login: z.boolean().optional(),
  is_oidc_active: z.boolean().optional(),
  updated_at: z.date().optional().nullable(),
  mfa_mandatory: z.boolean().optional().nullable(),
  allow_user_ai_config: z.boolean().optional(),
});

export type GlobalSettings = z.infer<typeof globalSettingsSchema>;
export type GlobalSettingsInitializer = z.infer<typeof globalSettingsInitializerSchema>;
export type GlobalSettingsMutator = z.infer<typeof globalSettingsMutatorSchema>;
