// Generated by ts-to-zod
import { z } from "zod";

export const mealsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.meals"),
  }),
);

const userIdSchema = z.any();

export const mealsSchema = z.object({
  id: mealsIdSchema,
  user_id: userIdSchema,
  name: z.string(),
  description: z.string().nullable(),
  is_public: z.boolean().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
  shared_with_public: z.boolean().nullable(),
  serving_size: z.number(),
  serving_unit: z.string(),
  total_servings: z.number(),
});

export const mealsInitializerSchema = z.object({
  id: mealsIdSchema.optional(),
  user_id: userIdSchema,
  name: z.string(),
  description: z.string().optional().nullable(),
  is_public: z.boolean().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  shared_with_public: z.boolean().optional().nullable(),
  serving_size: z.number().optional(),
  serving_unit: z.string().optional(),
  total_servings: z.number().optional(),
});

export const mealsMutatorSchema = z.object({
  id: mealsIdSchema.optional(),
  user_id: userIdSchema.optional(),
  name: z.string().optional(),
  description: z.string().optional().nullable(),
  is_public: z.boolean().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  shared_with_public: z.boolean().optional().nullable(),
  serving_size: z.number().optional(),
  serving_unit: z.string().optional(),
  total_servings: z.number().optional(),
});

export type Meals = z.infer<typeof mealsSchema>;
export type MealsInitializer = z.infer<typeof mealsInitializerSchema>;
export type MealsMutator = z.infer<typeof mealsMutatorSchema>;
