// Generated by ts-to-zod
// NOTE: The nutrition snapshot fields below (serving_size through
// custom_nutrients) were added manually for the meal_foods nutrition snapshot
// migration. There is no configured regen script — if ts-to-zod is run ad hoc
// in the future, re-add these fields.
import { z } from "zod";

export const mealFoodsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.meal_foods"),
  }),
);

const mealsIdSchema = z.any();

const foodsIdSchema = z.any();

const foodVariantsIdSchema = z.any();

// Shared optional nutrition snapshot fields added to meal_foods.
const mealFoodsNutritionSnapshotSchema = {
  serving_size:         z.number().nullable().optional(),
  serving_unit:         z.string().nullable().optional(),
  calories:             z.number().nullable().optional(),
  protein:              z.number().nullable().optional(),
  carbs:                z.number().nullable().optional(),
  fat:                  z.number().nullable().optional(),
  saturated_fat:        z.number().nullable().optional(),
  polyunsaturated_fat:  z.number().nullable().optional(),
  monounsaturated_fat:  z.number().nullable().optional(),
  trans_fat:            z.number().nullable().optional(),
  cholesterol:          z.number().nullable().optional(),
  sodium:               z.number().nullable().optional(),
  potassium:            z.number().nullable().optional(),
  dietary_fiber:        z.number().nullable().optional(),
  sugars:               z.number().nullable().optional(),
  vitamin_a:            z.number().nullable().optional(),
  vitamin_c:            z.number().nullable().optional(),
  calcium:              z.number().nullable().optional(),
  iron:                 z.number().nullable().optional(),
  glycemic_index:       z.string().nullable().optional(),
  custom_nutrients:     z.record(z.string(), z.union([z.string(), z.number()])).nullable().optional(),
};

export const mealFoodsSchema = z.object({
  id: mealFoodsIdSchema,
  meal_id: mealsIdSchema,
  food_id: foodsIdSchema,
  variant_id: foodVariantsIdSchema.nullable(),
  quantity: z.number(),
  unit: z.string(),
  created_at: z.date(),
  updated_at: z.date(),
  ...mealFoodsNutritionSnapshotSchema,
});

export const mealFoodsInitializerSchema = z.object({
  id: mealFoodsIdSchema.optional(),
  meal_id: mealsIdSchema,
  food_id: foodsIdSchema,
  variant_id: foodVariantsIdSchema.optional().nullable(),
  quantity: z.number(),
  unit: z.string(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  ...mealFoodsNutritionSnapshotSchema,
});

export const mealFoodsMutatorSchema = z.object({
  id: mealFoodsIdSchema.optional(),
  meal_id: mealsIdSchema.optional(),
  food_id: foodsIdSchema.optional(),
  variant_id: foodVariantsIdSchema.optional().nullable(),
  quantity: z.number().optional(),
  unit: z.string().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  ...mealFoodsNutritionSnapshotSchema,
});

export type MealFoods = z.infer<typeof mealFoodsSchema>;
export type MealFoodsInitializer = z.infer<typeof mealFoodsInitializerSchema>;
export type MealFoodsMutator = z.infer<typeof mealFoodsMutatorSchema>;
