// Generated by ts-to-zod
import { z } from "zod";

export const mealTypesIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.meal_types"),
  }),
);

const userIdSchema = z.any();

export const mealTypesSchema = z.object({
  id: mealTypesIdSchema,
  name: z.string(),
  user_id: userIdSchema.nullable(),
  sort_order: z.number().nullable(),
  created_at: z.date().nullable(),
  is_visible: z.boolean(),
  show_in_quick_log: z.boolean().nullable(),
});

export const mealTypesInitializerSchema = z.object({
  id: mealTypesIdSchema.optional(),
  name: z.string(),
  user_id: userIdSchema.optional().nullable(),
  sort_order: z.number().optional().nullable(),
  created_at: z.date().optional().nullable(),
  is_visible: z.boolean().optional(),
  show_in_quick_log: z.boolean().optional().nullable(),
});

export const mealTypesMutatorSchema = z.object({
  id: mealTypesIdSchema.optional(),
  name: z.string().optional(),
  user_id: userIdSchema.optional().nullable(),
  sort_order: z.number().optional().nullable(),
  created_at: z.date().optional().nullable(),
  is_visible: z.boolean().optional(),
  show_in_quick_log: z.boolean().optional().nullable(),
});

export type MealTypes = z.infer<typeof mealTypesSchema>;
export type MealTypesInitializer = z.infer<typeof mealTypesInitializerSchema>;
export type MealTypesMutator = z.infer<typeof mealTypesMutatorSchema>;
