// Generated by ts-to-zod
import { z } from "zod";

export const moodEntriesIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.mood_entries"),
  }),
);

const userIdSchema = z.any();

export const moodEntriesSchema = z.object({
  id: moodEntriesIdSchema,
  user_id: userIdSchema,
  mood_value: z.number(),
  notes: z.string().nullable(),
  entry_date: z.date(),
  created_at: z.date(),
  updated_at: z.date(),
  created_by_user_id: userIdSchema.nullable(),
  updated_by_user_id: userIdSchema.nullable(),
});

export const moodEntriesInitializerSchema = z.object({
  id: moodEntriesIdSchema.optional(),
  user_id: userIdSchema,
  mood_value: z.number(),
  notes: z.string().optional().nullable(),
  entry_date: z.date().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
});

export const moodEntriesMutatorSchema = z.object({
  id: moodEntriesIdSchema.optional(),
  user_id: userIdSchema.optional(),
  mood_value: z.number().optional(),
  notes: z.string().optional().nullable(),
  entry_date: z.date().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  created_by_user_id: userIdSchema.optional().nullable(),
  updated_by_user_id: userIdSchema.optional().nullable(),
});

export type MoodEntries = z.infer<typeof moodEntriesSchema>;
export type MoodEntriesInitializer = z.infer<typeof moodEntriesInitializerSchema>;
export type MoodEntriesMutator = z.infer<typeof moodEntriesMutatorSchema>;
