// Generated by ts-to-zod
import { z } from "zod";

export const onboardingStatusIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.onboarding_status"),
  }),
);

const userIdSchema = z.any();

export const onboardingStatusSchema = z.object({
  id: onboardingStatusIdSchema,
  user_id: userIdSchema,
  full_name: z.string().nullable(),
  onboarding_complete: z.boolean(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
});

export const onboardingStatusInitializerSchema = z.object({
  id: onboardingStatusIdSchema.optional(),
  user_id: userIdSchema,
  full_name: z.string().optional().nullable(),
  onboarding_complete: z.boolean().optional(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const onboardingStatusMutatorSchema = z.object({
  id: onboardingStatusIdSchema.optional(),
  user_id: userIdSchema.optional(),
  full_name: z.string().optional().nullable(),
  onboarding_complete: z.boolean().optional(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export type OnboardingStatus = z.infer<typeof onboardingStatusSchema>;
export type OnboardingStatusInitializer = z.infer<typeof onboardingStatusInitializerSchema>;
export type OnboardingStatusMutator = z.infer<typeof onboardingStatusMutatorSchema>;
