// Generated by ts-to-zod
import { z } from "zod";

export const sparkyChatHistorySchema = z.object({
  id: z.string(),
  user_id: z.string(),
  session_id: z.string(),
  message_type: z.string(),
  content: z.string(),
  image_url: z.string().nullable(),
  metadata: z.unknown().nullable(),
  created_at: z.date(),
  message: z.string().nullable(),
  response: z.string().nullable(),
  parts: z.array(z.unknown()).nullable(),
});

export const sparkyChatHistoryInitializerSchema = z.object({
  id: z.string().optional(),
  user_id: z.string(),
  session_id: z.string().optional(),
  message_type: z.string(),
  content: z.string(),
  image_url: z.string().optional().nullable(),
  metadata: z.unknown().optional().nullable(),
  created_at: z.date().optional(),
  message: z.string().optional().nullable(),
  response: z.string().optional().nullable(),
  parts: z.array(z.unknown()).optional().nullable(),
});

export const sparkyChatHistoryMutatorSchema = z.object({
  id: z.string().optional(),
  user_id: z.string().optional(),
  session_id: z.string().optional(),
  message_type: z.string().optional(),
  content: z.string().optional(),
  image_url: z.string().optional().nullable(),
  metadata: z.unknown().optional().nullable(),
  created_at: z.date().optional(),
  message: z.string().optional().nullable(),
  response: z.string().optional().nullable(),
  parts: z.array(z.unknown()).optional().nullable(),
});

export type SparkyChatHistory = z.infer<typeof sparkyChatHistorySchema>;
export type SparkyChatHistoryInitializer = z.infer<typeof sparkyChatHistoryInitializerSchema>;
export type SparkyChatHistoryMutator = z.infer<typeof sparkyChatHistoryMutatorSchema>;
