// Generated by ts-to-zod
import { z } from "zod";

const userIdSchema = z.any();

const mealTypesIdSchema = z.any();

export const userMealVisibilitiesSchema = z.object({
  user_id: userIdSchema,
  meal_type_id: mealTypesIdSchema,
  is_visible: z.boolean().nullable(),
  created_at: z.date().nullable(),
  show_in_quick_log: z.boolean().nullable(),
});

export const userMealVisibilitiesInitializerSchema = z.object({
  user_id: userIdSchema,
  meal_type_id: mealTypesIdSchema,
  is_visible: z.boolean().optional().nullable(),
  created_at: z.date().optional().nullable(),
  show_in_quick_log: z.boolean().optional().nullable(),
});

export const userMealVisibilitiesMutatorSchema = z.object({
  user_id: userIdSchema.optional(),
  meal_type_id: mealTypesIdSchema.optional(),
  is_visible: z.boolean().optional().nullable(),
  created_at: z.date().optional().nullable(),
  show_in_quick_log: z.boolean().optional().nullable(),
});

export type UserMealVisibilities = z.infer<typeof userMealVisibilitiesSchema>;
export type UserMealVisibilitiesInitializer = z.infer<typeof userMealVisibilitiesInitializerSchema>;
export type UserMealVisibilitiesMutator = z.infer<typeof userMealVisibilitiesMutatorSchema>;
