// Generated by ts-to-zod
import { z } from "zod";

export const userNutrientGoalPreferencesIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.user_nutrient_goal_preferences"),
  }),
);

const userIdSchema = z.any();

export const nutrientGoalTypeSchema = z.enum(["minimum", "maximum", "target"]);

export const userNutrientGoalPreferencesSchema = z.object({
  id: userNutrientGoalPreferencesIdSchema,
  user_id: userIdSchema,
  nutrient_key: z.string(),
  goal_type: nutrientGoalTypeSchema,
  target_min: z.number().nullable(),
  target_max: z.number().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const userNutrientGoalPreferencesInitializerSchema = z.object({
  id: userNutrientGoalPreferencesIdSchema.optional(),
  user_id: userIdSchema,
  nutrient_key: z.string(),
  goal_type: nutrientGoalTypeSchema,
  target_min: z.number().nullable().optional(),
  target_max: z.number().nullable().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export const userNutrientGoalPreferencesMutatorSchema = z.object({
  id: userNutrientGoalPreferencesIdSchema.optional(),
  user_id: userIdSchema.optional(),
  nutrient_key: z.string().optional(),
  goal_type: nutrientGoalTypeSchema.optional(),
  target_min: z.number().nullable().optional(),
  target_max: z.number().nullable().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export type NutrientGoalType = z.infer<typeof nutrientGoalTypeSchema>;
export type UserNutrientGoalPreferences = z.infer<typeof userNutrientGoalPreferencesSchema>;
export type UserNutrientGoalPreferencesInitializer = z.infer<typeof userNutrientGoalPreferencesInitializerSchema>;
export type UserNutrientGoalPreferencesMutator = z.infer<typeof userNutrientGoalPreferencesMutatorSchema>;
