// Generated by ts-to-zod
import { z } from "zod";
import {
  CALORIE_SAFETY_FLOOR_MODES,
  MAX_CALORIE_SAFETY_FLOOR,
  MIN_CALORIE_SAFETY_FLOOR,
} from "../../constants/calorieConstants.ts";
import { CHART_SCALE_MODES } from "../../constants/chartConstants.ts";

export const SUPPORTED_TIME_FORMATS = ["HH:mm", "h:mm A", "h:mm a"] as const;

const externalDataProvidersIdSchema = z.any();

export const userPreferencesSchema = z.object({
  id: z.string(),
  user_id: z.string(),
  date_format: z.string(),
  time_format: z.enum(SUPPORTED_TIME_FORMATS),
  default_weight_unit: z.string(),
  default_measurement_unit: z.string(),
  created_at: z.date(),
  updated_at: z.date(),
  auto_clear_history: z.string().nullable(),
  logging_level: z.string().nullable(),
  timezone: z.string().nullable(),
  default_food_data_provider_id: z.string().nullable(),
  item_display_limit: z.number(),
  water_display_unit: z.string().nullable(),
  bmr_algorithm: z.string(),
  body_fat_algorithm: z.string(),
  include_bmr_in_net_calories: z.boolean(),
  show_net_carbs: z.boolean(),
  food_search_all_providers_default: z.boolean(),
  default_distance_unit: z.string(),
  language: z.string().nullable(),
  calorie_goal_adjustment_mode: z.string().nullable(),
  energy_unit: z.string(),
  fat_breakdown_algorithm: z.string(),
  mineral_calculation_algorithm: z.string(),
  vitamin_calculation_algorithm: z.string(),
  sugar_calculation_algorithm: z.string(),
  added_sugar_algorithm: z.string(),
  auto_scale_open_food_facts_imports: z.boolean().nullable(),
  exercise_calorie_percentage: z.number().nullable(),
  activity_level: z.string().nullable(),
  tdee_allow_negative_adjustment: z.boolean().nullable(),
  default_barcode_provider_id: externalDataProvidersIdSchema.nullable(),
  first_day_of_week: z.number().int().min(0).max(6).nullable().optional(),
  ai_assisted_conversions: z.boolean(),
  goal_mode: z.enum([
    "maintain",
    "recomp",
    "cut",
    "high_cut",
    "lean_bulk",
    "bulk",
    "manual",
  ]),
  goal_mode_calculation_method: z.enum(["adaptive", "manual"]),
  goal_mode_custom_percentage: z.number().int().min(-40).max(40),
  calorie_safety_floor_mode: z.enum(CALORIE_SAFETY_FLOOR_MODES),
  calorie_safety_floor_value: z
    .number()
    .int()
    .min(MIN_CALORIE_SAFETY_FLOOR)
    .max(MAX_CALORIE_SAFETY_FLOOR),
  chart_scale_mode: z.enum(CHART_SCALE_MODES),
  measurement_decimal_places: z.number().int().min(0),
  // Manually added (file is ts-to-zod generated; precedent: MealFoods.zod.ts). Keep on regen.
  use_external_bmr: z.boolean(),
  active_ai_service_id: z.string().uuid().nullable().optional(),
  active_vision_ai_service_id: z.string().uuid().nullable().optional(),
  auto_scale_online_imports: z.boolean().nullable().optional(),
  barcode_fallback_open_food_facts: z.boolean().nullable().optional(),
  add_exercise_water_to_goal: z.boolean().nullable().optional(),
});

export const userPreferencesInitializerSchema = z.object({
  id: z.string().optional(),
  user_id: z.string(),
  date_format: z.string().optional(),
  time_format: z.enum(SUPPORTED_TIME_FORMATS).optional(),
  default_weight_unit: z.string().optional(),
  default_measurement_unit: z.string().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  auto_clear_history: z.string().optional().nullable(),
  logging_level: z.string().optional().nullable(),
  timezone: z.string().optional().nullable(),
  default_food_data_provider_id: z.string().optional().nullable(),
  item_display_limit: z.number().optional(),
  water_display_unit: z.string().optional().nullable(),
  bmr_algorithm: z.string().optional(),
  body_fat_algorithm: z.string().optional(),
  include_bmr_in_net_calories: z.boolean().optional(),
  show_net_carbs: z.boolean().optional(),
  food_search_all_providers_default: z.boolean().optional(),
  default_distance_unit: z.string().optional(),
  language: z.string().optional().nullable(),
  calorie_goal_adjustment_mode: z.string().optional().nullable(),
  energy_unit: z.string().optional(),
  fat_breakdown_algorithm: z.string().optional(),
  mineral_calculation_algorithm: z.string().optional(),
  vitamin_calculation_algorithm: z.string().optional(),
  sugar_calculation_algorithm: z.string().optional(),
  added_sugar_algorithm: z.string().optional(),
  auto_scale_open_food_facts_imports: z.boolean().optional().nullable(),
  exercise_calorie_percentage: z.number().optional().nullable(),
  activity_level: z.string().optional().nullable(),
  tdee_allow_negative_adjustment: z.boolean().optional().nullable(),
  default_barcode_provider_id: externalDataProvidersIdSchema
    .optional()
    .nullable(),
  first_day_of_week: z.number().int().min(0).max(6).nullable().optional(),
  ai_assisted_conversions: z.boolean().optional(),
  goal_mode: z
    .enum([
      "maintain",
      "recomp",
      "cut",
      "high_cut",
      "lean_bulk",
      "bulk",
      "manual",
    ])
    .optional(),
  goal_mode_calculation_method: z.enum(["adaptive", "manual"]).optional(),
  goal_mode_custom_percentage: z.number().int().min(-40).max(40).optional(),
  calorie_safety_floor_mode: z.enum(CALORIE_SAFETY_FLOOR_MODES).optional(),
  calorie_safety_floor_value: z
    .number()
    .int()
    .min(MIN_CALORIE_SAFETY_FLOOR)
    .max(MAX_CALORIE_SAFETY_FLOOR)
    .optional(),
  chart_scale_mode: z.enum(CHART_SCALE_MODES).optional(),
  measurement_decimal_places: z.number().int().min(0).optional(),
  use_external_bmr: z.boolean().optional(),
  active_ai_service_id: z.string().uuid().nullable().optional(),
  active_vision_ai_service_id: z.string().uuid().nullable().optional(),
  auto_scale_online_imports: z.boolean().optional().nullable(),
  barcode_fallback_open_food_facts: z.boolean().optional().nullable(),
  add_exercise_water_to_goal: z.boolean().optional().nullable(),
});

export const userPreferencesMutatorSchema = z.object({
  id: z.string().optional(),
  user_id: z.string().optional(),
  date_format: z.string().optional(),
  time_format: z.enum(SUPPORTED_TIME_FORMATS).optional(),
  default_weight_unit: z.string().optional(),
  default_measurement_unit: z.string().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  auto_clear_history: z.string().optional().nullable(),
  logging_level: z.string().optional().nullable(),
  timezone: z.string().optional().nullable(),
  default_food_data_provider_id: z.string().optional().nullable(),
  item_display_limit: z.number().optional(),
  water_display_unit: z.string().optional().nullable(),
  bmr_algorithm: z.string().optional(),
  body_fat_algorithm: z.string().optional(),
  include_bmr_in_net_calories: z.boolean().optional(),
  show_net_carbs: z.boolean().optional(),
  food_search_all_providers_default: z.boolean().optional(),
  default_distance_unit: z.string().optional(),
  language: z.string().optional().nullable(),
  calorie_goal_adjustment_mode: z.string().optional().nullable(),
  energy_unit: z.string().optional(),
  fat_breakdown_algorithm: z.string().optional(),
  mineral_calculation_algorithm: z.string().optional(),
  vitamin_calculation_algorithm: z.string().optional(),
  sugar_calculation_algorithm: z.string().optional(),
  added_sugar_algorithm: z.string().optional(),
  auto_scale_open_food_facts_imports: z.boolean().optional().nullable(),
  exercise_calorie_percentage: z.number().optional().nullable(),
  activity_level: z.string().optional().nullable(),
  tdee_allow_negative_adjustment: z.boolean().optional().nullable(),
  default_barcode_provider_id: externalDataProvidersIdSchema
    .optional()
    .nullable(),
  first_day_of_week: z.number().int().min(0).max(6).nullable().optional(),
  ai_assisted_conversions: z.boolean().optional(),
  goal_mode: z
    .enum([
      "maintain",
      "recomp",
      "cut",
      "high_cut",
      "lean_bulk",
      "bulk",
      "manual",
    ])
    .optional(),
  goal_mode_calculation_method: z.enum(["adaptive", "manual"]).optional(),
  goal_mode_custom_percentage: z.number().int().min(-40).max(40).optional(),
  calorie_safety_floor_mode: z.enum(CALORIE_SAFETY_FLOOR_MODES).optional(),
  calorie_safety_floor_value: z
    .number()
    .int()
    .min(MIN_CALORIE_SAFETY_FLOOR)
    .max(MAX_CALORIE_SAFETY_FLOOR)
    .optional(),
  chart_scale_mode: z.enum(CHART_SCALE_MODES).optional(),
  measurement_decimal_places: z.number().int().min(0).optional(),
  use_external_bmr: z.boolean().optional(),
  active_ai_service_id: z.string().uuid().nullable().optional(),
  active_vision_ai_service_id: z.string().uuid().nullable().optional(),
  auto_scale_online_imports: z.boolean().optional().nullable(),
  barcode_fallback_open_food_facts: z.boolean().optional().nullable(),
  add_exercise_water_to_goal: z.boolean().optional().nullable(),
});

export type UserPreferences = z.infer<typeof userPreferencesSchema>;
export type UserPreferencesInitializer = z.infer<
  typeof userPreferencesInitializerSchema
>;
export type UserPreferencesMutator = z.infer<
  typeof userPreferencesMutatorSchema
>;
