// Generated by ts-to-zod
import { z } from "zod";

export const userCustomNutrientsIdSchema = z.string().and(
  z.object({
    __brand: z.literal("public.user_custom_nutrients"),
  }),
);

const userIdSchema = z.any();

export const userCustomNutrientsSchema = z.object({
  id: userCustomNutrientsIdSchema,
  user_id: userIdSchema,
  name: z.string(),
  unit: z.string(),
  created_at: z.date(),
  updated_at: z.date(),
});

export const userCustomNutrientsInitializerSchema = z.object({
  id: userCustomNutrientsIdSchema.optional(),
  user_id: userIdSchema,
  name: z.string(),
  unit: z.string(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export const userCustomNutrientsMutatorSchema = z.object({
  id: userCustomNutrientsIdSchema.optional(),
  user_id: userIdSchema.optional(),
  name: z.string().optional(),
  unit: z.string().optional(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
});

export type UserCustomNutrients = z.infer<typeof userCustomNutrientsSchema>;
export type UserCustomNutrientsInitializer = z.infer<typeof userCustomNutrientsInitializerSchema>;
export type UserCustomNutrientsMutator = z.infer<typeof userCustomNutrientsMutatorSchema>;
