// Generated by ts-to-zod
import { z } from "zod";

const userIdSchema = z.any();

export const waterIntakeEntriesSchema = z.object({
  id: z.string(),
  user_id: z.string(),
  entry_date: z.date(),
  water_ml: z.number(),
  container_id: z.number().nullable(),
  container_name: z.string().nullable(),
  source: z.string(),
  source_id: z.string().nullable(),
  created_at: z.date(),
  created_by_user_id: userIdSchema.nullable(),
  logged_at: z.date(),
});

export const waterIntakeEntriesInitializerSchema = z.object({
  id: z.string().optional(),
  user_id: z.string(),
  entry_date: z.date().optional(),
  water_ml: z.number(),
  container_id: z.number().optional().nullable(),
  container_name: z.string().optional().nullable(),
  source: z.string().optional(),
  source_id: z.string().optional().nullable(),
  created_at: z.date().optional(),
  created_by_user_id: userIdSchema.optional().nullable(),
  logged_at: z.date().optional(),
});

export const waterIntakeEntriesMutatorSchema = z.object({
  id: z.string().optional(),
  user_id: z.string().optional(),
  entry_date: z.date().optional(),
  water_ml: z.number().optional(),
  container_id: z.number().optional().nullable(),
  container_name: z.string().optional().nullable(),
  source: z.string().optional(),
  source_id: z.string().optional().nullable(),
  created_at: z.date().optional(),
  created_by_user_id: userIdSchema.optional().nullable(),
  logged_at: z.date().optional(),
});

export type WaterIntakeEntries = z.infer<typeof waterIntakeEntriesSchema>;
export type WaterIntakeEntriesInitializer = z.infer<typeof waterIntakeEntriesInitializerSchema>;
export type WaterIntakeEntriesMutator = z.infer<typeof waterIntakeEntriesMutatorSchema>;
