// Generated by ts-to-zod
import { z } from "zod";

export const workoutPresetExercisesIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.workout_preset_exercises"),
  }),
);

const workoutPresetsIdSchema = z.any();

const exercisesIdSchema = z.any();

export const workoutPresetExercisesSchema = z.object({
  id: workoutPresetExercisesIdSchema,
  workout_preset_id: workoutPresetsIdSchema,
  exercise_id: exercisesIdSchema,
  image_url: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
  sort_order: z.number().nullable(),
});

export const workoutPresetExercisesInitializerSchema = z.object({
  id: workoutPresetExercisesIdSchema.optional(),
  workout_preset_id: workoutPresetsIdSchema,
  exercise_id: exercisesIdSchema,
  image_url: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  sort_order: z.number().optional().nullable(),
});

export const workoutPresetExercisesMutatorSchema = z.object({
  id: workoutPresetExercisesIdSchema.optional(),
  workout_preset_id: workoutPresetsIdSchema.optional(),
  exercise_id: exercisesIdSchema.optional(),
  image_url: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
  sort_order: z.number().optional().nullable(),
});

export type WorkoutPresetExercises = z.infer<typeof workoutPresetExercisesSchema>;
export type WorkoutPresetExercisesInitializer = z.infer<typeof workoutPresetExercisesInitializerSchema>;
export type WorkoutPresetExercisesMutator = z.infer<typeof workoutPresetExercisesMutatorSchema>;
