// Generated by ts-to-zod
import { z } from "zod";

export const workoutPresetExerciseSetsIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.workout_preset_exercise_sets"),
  }),
);

const workoutPresetExercisesIdSchema = z.any();

export const workoutPresetExerciseSetsSchema = z.object({
  id: workoutPresetExerciseSetsIdSchema,
  workout_preset_exercise_id: workoutPresetExercisesIdSchema,
  set_number: z.number(),
  set_type: z.string().nullable(),
  reps: z.number().nullable(),
  weight: z.number().nullable(),
  duration: z.number().nullable(),
  rest_time: z.number().nullable(),
  notes: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
});

export const workoutPresetExerciseSetsInitializerSchema = z.object({
  id: workoutPresetExerciseSetsIdSchema.optional(),
  workout_preset_exercise_id: workoutPresetExercisesIdSchema,
  set_number: z.number(),
  set_type: z.string().optional().nullable(),
  reps: z.number().optional().nullable(),
  weight: z.number().optional().nullable(),
  duration: z.number().optional().nullable(),
  rest_time: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const workoutPresetExerciseSetsMutatorSchema = z.object({
  id: workoutPresetExerciseSetsIdSchema.optional(),
  workout_preset_exercise_id: workoutPresetExercisesIdSchema.optional(),
  set_number: z.number().optional(),
  set_type: z.string().optional().nullable(),
  reps: z.number().optional().nullable(),
  weight: z.number().optional().nullable(),
  duration: z.number().optional().nullable(),
  rest_time: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export type WorkoutPresetExerciseSets = z.infer<typeof workoutPresetExerciseSetsSchema>;
export type WorkoutPresetExerciseSetsInitializer = z.infer<typeof workoutPresetExerciseSetsInitializerSchema>;
export type WorkoutPresetExerciseSetsMutator = z.infer<typeof workoutPresetExerciseSetsMutatorSchema>;
