// Generated by ts-to-zod
import { z } from "zod";

export const workoutPlanAssignmentSetsIdSchema = z.number().and(
  z.object({
    __brand: z.literal("public.workout_plan_assignment_sets"),
  }),
);

const workoutPlanTemplateAssignmentsIdSchema = z.any();

export const workoutPlanAssignmentSetsSchema = z.object({
  id: workoutPlanAssignmentSetsIdSchema,
  assignment_id: workoutPlanTemplateAssignmentsIdSchema,
  set_number: z.number(),
  set_type: z.string().nullable(),
  reps: z.number().nullable(),
  weight: z.number().nullable(),
  duration: z.number().nullable(),
  rest_time: z.number().nullable(),
  notes: z.string().nullable(),
  created_at: z.date().nullable(),
  updated_at: z.date().nullable(),
});

export const workoutPlanAssignmentSetsInitializerSchema = z.object({
  id: workoutPlanAssignmentSetsIdSchema.optional(),
  assignment_id: workoutPlanTemplateAssignmentsIdSchema,
  set_number: z.number(),
  set_type: z.string().optional().nullable(),
  reps: z.number().optional().nullable(),
  weight: z.number().optional().nullable(),
  duration: z.number().optional().nullable(),
  rest_time: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export const workoutPlanAssignmentSetsMutatorSchema = z.object({
  id: workoutPlanAssignmentSetsIdSchema.optional(),
  assignment_id: workoutPlanTemplateAssignmentsIdSchema.optional(),
  set_number: z.number().optional(),
  set_type: z.string().optional().nullable(),
  reps: z.number().optional().nullable(),
  weight: z.number().optional().nullable(),
  duration: z.number().optional().nullable(),
  rest_time: z.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  created_at: z.date().optional().nullable(),
  updated_at: z.date().optional().nullable(),
});

export type WorkoutPlanAssignmentSets = z.infer<typeof workoutPlanAssignmentSetsSchema>;
export type WorkoutPlanAssignmentSetsInitializer = z.infer<typeof workoutPlanAssignmentSetsInitializerSchema>;
export type WorkoutPlanAssignmentSetsMutator = z.infer<typeof workoutPlanAssignmentSetsMutatorSchema>;
